Django version 5.1.1, using settings 'dqaas_api.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

2025-03-21 00:11:57,686 - INFO - 📂 Received FILES: <MultiValueDict: {'file': [<InMemoryUploadedFile: file.txt (text/plain)>]}>
2025-03-21 00:11:57,797 - INFO - 📌 Executing query: INSERT INTO vz-it-np-izcv-dev-idmcdo-0.dga_dq_tbls.dqaas_profile_rpt
(
    rpt_seq_num, prfl_id, prfl_type, dq_pillar, src_tbl, meas_name,
    data_dt, feature_name, grouped_columns, count_curr, prfl_run_ts, weekday
)
SELECT
    900098 AS rpt_seq_num,
    7851 AS prfl_id,
    'CUSTOM_RULES' AS prfl_type,
    'Consistency' AS dq_pillar,
    'CUST_ACCT_LINE_ADDR_V' AS src_tbl,
    'CUST_ACCT_LINE_ADDR_V Table count' AS meas_name,
    CAST(LAST_UPD_DT AS DATE) AS data_dt,
    'Tier1 Models' AS feature_name,
    NULL AS grouped_columns,
    COUNT(*) AS count_curr,
    CURRENT_TIMESTAMP AS prfl_run_ts,
    DAYOFWEEK(CAST(LAST_UPD_DT AS DATE)) AS weekday
FROM NTL_PRD_ALLVM.CUST_ACCT_LINE_ADDR_V
WHERE CAST(LAST_UPD_DT AS DATE) >= CURRENT_DATE - 90
GROUP BY 1,2,3,4,5,6,7,8,11,12
2025-03-21 00:12:01,322 - ERROR - ❌ Query execution failed: INSERT INTO vz-it-np-izcv-dev-idmcdo-0.dga_dq_tbls.dqaas_profile_rpt
(
    rpt_seq_num, prfl_id, prfl_type, dq_pillar, src_tbl, meas_name,
    data_dt, feature_name, grouped_columns, count_curr, prfl_run_ts, weekday
)
SELECT
    900098 AS rpt_seq_num,
    7851 AS prfl_id,
    'CUSTOM_RULES' AS prfl_type,
    'Consistency' AS dq_pillar,
    'CUST_ACCT_LINE_ADDR_V' AS src_tbl,
    'CUST_ACCT_LINE_ADDR_V Table count' AS meas_name,
    CAST(LAST_UPD_DT AS DATE) AS data_dt,
    'Tier1 Models' AS feature_name,
    NULL AS grouped_columns,
    COUNT(*) AS count_curr,
    CURRENT_TIMESTAMP AS prfl_run_ts,
    DAYOFWEEK(CAST(LAST_UPD_DT AS DATE)) AS weekday
FROM NTL_PRD_ALLVM.CUST_ACCT_LINE_ADDR_V
WHERE CAST(LAST_UPD_DT AS DATE) >= CURRENT_DATE - 90
GROUP BY 1,2,3,4,5,6,7,8,11,12
Error: [Version 20.0.0.15] [Session 243715834] [Teradata Database] [Error 3707] Syntax error, expected something like a 'SELECT' keyword or a 'TRANSACTIONTIME' keyword or a 'NONTEMPORAL' keyword or 'AS' keyword between the word 'vz' and '-'.
 at gosqldriver/teradatasql.formatError ErrorUtil.go:91
 at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError ErrorUtil.go:251
 at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError ErrorUtil.go:267
 at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:715
 at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:2308
 at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:874
 at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:720
 at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122
 at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:1225
 at database/sql.ctxDriverQuery ctxutil.go:48
 at database/sql.(*DB).queryDC.func1 sql.go:1776
 at database/sql.withLock sql.go:3530
 at database/sql.(*DB).queryDC sql.go:1771
 at database/sql.(*Conn).QueryContext sql.go:2027
 at main.createRows goside.go:783
 at main.goCreateRows goside.go:662
 at _cgoexp_97cde1c53cf8_goCreateRows _cgo_gotypes.go:389
 at runtime.cgocallbackg1 cgocall.go:420
 at runtime.cgocallbackg cgocall.go:339
 at runtime.cgocallback asm_amd64.s:1079
 at runtime.goexit asm_amd64.s:1695
Internal Server Error: /mle/ExecuteHistorySQL/
2025-03-21 00:12:01,326 - ERROR - Internal Server Error: /mle/ExecuteHistorySQL/
[21/Mar/2025 00:12:01] "POST /mle/ExecuteHistorySQL/ HTTP/1.1" 500 1543




