    def log_failure(self, table_id, table_name, run_count, data_date, error_message):
        """
        Log any failures into the failure report table.
        """
        run_ts = datetime.now()
        run_status = 'Failure'
        query = f"""
            INSERT INTO {self.dq_gcp_data_project_id}.{self.dq_bq_dataset}.{self.failure_rpt_table} (table_id, table_name, run_ts, data_date, run_count, run_status, error_msg)
            VALUES ({table_id}, '{table_name}', '{run_ts}', '{data_date}', {run_count}, '{run_status}' , '{error_message}')
        """
        self.logger.info(query)
        try:
            self.client.query(query).result()
            self.logger.info(f"Inserted failure record for table {table_name}")
        except Exception as e:
            self.logger.error(f"Error logging to failure report table: {str(e)}")
            raise
